### ISSUE TITLE
Fail to work properly on Android

### ISSUE THREAD

**Issue by TonyMaYiXuan** [TonyMaYiXuan/Tony_notes#12]
When I click button 'Home' when it is currently displaying a pdf file, it only shows _START_ with nothing else.

**Comment by TonyMaYiXuan** [comment]
Test on computer with _isAndroid = true_, when error occur the page is not successfully loaded:
```Uncaught DOMException: Blocked a frame with origin "https://tonymayixuan.github.io" from accessing a cross-origin frame.```
    ```at dayNightMode (https://tonymayixuan.github.io/Tony_notes/dayNightMode.js:29:69)```
    ```at goHomePage (https://tonymayixuan.github.io/Tony_notes/goHomePage.js:34:5)```
    ```at HTMLButtonElement.onclick (https://tonymayixuan.github.io/Tony_notes/:39:84)```

**Comment by TonyMaYiXuan** [comment]
Should be fixed now: commit 09169c6.

**Comment by TonyMaYiXuan** [comment]
Should be fixed now: commit cdfb89bddbb9350ed5917ada5e124564e94c39d7
